config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/terms", to: "static_pages#terms"

  get "search", to: "searches#search"
  get "search_result", to: "searches#search_result"
  get "category_search", to: "searches#category_search"
  get "birthday_search", to: "searches#birthday_search"
  get "searches/:id", to: "searches#show"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :sub_categories
end

app/models/flower.rb
class Flower < ApplicationRecord
    has_many :flower_words
end

app/models/flower_word.rb
class FlowerWord < ApplicationRecord
    belongs_to :flower
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

def search
    @range = params[:range]
    if @range == "花の名前"
        @flowers = Flower.where("name like ?", "%#{params[:word]}%").page(params[:page]).per(12)
        render "/searches/search_result"
    else
        @flower_words = FlowerWord.where("word like ?", "%#{params[:word]}%")
        @flowers = Set.new
        @flower_words.each do |word|
            @flowers.add(Flower.find(word.flower_id))
        end
        @flowers = @flowers.to_a
        @flowers = Kaminari.paginate_array(@flowers).page(params[:page]).per(12)
        render "/searches/search_result"
    end
end

def search_result
end

def category_search
    @sub_category = SubCategory.find(params[:sub_category])
    @flowers = Flower.where("sub_category_id like ?", "%,#{@sub_category.id},%").page(params[:page]).per(12)
    render "/searches/search_result"
end

def birthday_search
    @birthday = params["birthday(2i)"].to_i * 100 + params["birthday(3i)"].to_i
    @birthday = sprintf("%04d", @birthday)
    @flowers = Flower.where("date like ?", "%#{@birthday}%").page(params[:page]).per(12)
    render "/searches/search_result"
end

def show
    @flower = Flower.find(params[:id])
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def make_number_to_date(number)
        month = number[0,2].to_i
        day = number[2,4].to_i
        return "#{month}月#{day}日"
    end

    def get_birthdays(numbers)
        number_array = numbers.split(",")
        birthdays = []
        number_array.each do |number|
            birthdays.append(make_number_to_date(number))
        end
        return birthdays
    end

    def get_flower_words(id)
        flower_words = FlowerWord.where(flower_id: id)
        words = []
        flower_words.each do |flower_word|
            words.append("「" + flower_word[:word] + "」")
        end
        return words
    end

    def get_situations(numbers)
        situations = []
        sub_category_id = numbers.split(",")[1..-1].map!{|x| x.to_i}
        sub_category_id.each do |id|
            situations.append(SubCategory.find(id)[:name])
        end
        return situations
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
    <ul>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></>
    </ul>
</footer>

app/views/layouts/_header.html.erb
<header class="l-header">
    <div class="l-header-inner">
        <div class="l-header-logo">
            <%= link_to "Youth and Flower", root_path %>
        </div>
        <nav class="l-header-nav">
            <ul class="l-header-nav-list">
                <li><%= render "layouts/search_window" %></li>
                <li class="menu-item"><%= link_to "ABOUT", "#" %></li>
                <li class="menu-item"><%= link_to "TOPICS", "#" %></li>
                <li class="menu-item"><%= link_to "RANKING", "#" %></li>
                <li class="menu-item"><%= link_to "NEWS", "#" %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_search_window.html.erb
<div class="search-form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word, placeholder: "キーワードを入力", class: "text" %>
        <%= f.select :range, options_for_select([["花の名前"], ["花言葉"]]) %>
        <%= button_tag type: "submit", class: "btn btn-primary" do %>
            <i class="fa fa-search"></i>
        <% end %>
    <% end %>
</div>

app/views/layouts/_selectbox.html.erb
<%= form_with url: category_search_path, local: true, method: :get do |f| %>
    <div class="category-select">
        <%= f.collection_select :category, Category.all, :id, :name, include_blank: "目的から探す" %>
    </div>
    
    <div id="sub_category">
        <%= f.select :sub_category, [], include_blank: "目的から探す", class: "default-sub-category-select" %>
    </div>
    
    <%= f.submit "検索", class: "category-btn" %>

    <% Category.all.each do |category| %>
        <template id="sub-category-of-category<%= category.id %>">
            <%= f.collection_select :sub_category, category.sub_categories, :id, :name, include_blank: "目的から探す" %>
        </template>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://kit.fontawesome.com/2f65f7c47a.js" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <div class="debug">
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>

app/views/searches/search_result.html.erb
<h2>検索結果</h2>

<div class="column">
    <ul class="items">
        <% @flowers.each do |flower| %>
            <li class="image-and-link">
                <ul>
                    <li><%= link_to image_tag("#{flower.image_url}", class: "flower-images"), "/searches/#{flower.id}" %></li>
                    <li><%= link_to flower.name, "/searches/#{flower.id}" %></li>
                </ul>
            </li>
        <% end %>
    </ul>
    <%= paginate @flowers %>
</div>

app/views/searches/show.html.erb
<h2 class="flower-name"><%= @flower.name %></h2>

<div class="top-detail">
    <%= image_tag "#{@flower.image_url}", class: "flower-image" %>
    <div class="words-birthday-situation">
        <h4>全般の花言葉</h4>
        <% get_flower_words(@flower.id).each do |word| %>
            <p class="flower_word"><%= word %></p>
        <% end %>

        <h4>いつの誕生花</h4>
        <% get_birthdays(@flower.date).each do |birthday| %>
            <p class="birthday"><%= birthday %></p>
        <% end %>

        <h4>適した場面</h4>
        <% get_situations(@flower.sub_category_id).each do |situation| %>
            <p class="situation"><%= situation %></p>
        <% end %>
    </div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>
<p>一応、フォーム用意しとくか</p>

app/views/static_pages/home.html.erb
<main class="main-contents">
    <div class="top-image-area">
        <div class="top-image">
            <div class="slider-item"><%= image_tag "top_image1.jpg", class: "pic" %></div>
            <div class="slider-item"><%= image_tag "top_image2.jpg", class: "pic" %></div>
            <div class="slider-item"><%= image_tag "top_image3.jpg", class: "pic" %></div>
        </div>
        <div class="top-message">
            <p>誕生日から、イベントから</p>
            <p class="message">誰かに贈る、<br>
            お花を探されるあなたへ</p>
        </div>
    </div>

    <div class="select-box-area">
        <%= render "layouts/selectbox" %>
    </div>

    <div class="about">
        <h2>About</h2>
        <h3>若者と花屋をつなぐ</h3>
        <p>このサイトのコンセプト</p>
        <p>伝えたいメッセージ</p>
        <p>言いたいこと、叶えたい思い</p>
    </div>

    <div class="topics">
        <h2>Topics</h2>
    </div>

    <div class="ranking">
        <h2>Ranking</h2>
    </div>

    <div class="birthday-search">
        <%= form_with url: birthday_search_path, local: true, method: :get do |f| %>
            <%= f.date_select :birthday, use_month_numbers: true, discard_year: true, prompt: "--" %>
            <%= f.submit "検索" %>
        <% end %>
    </div>
</main>